baseurl = "http://jamesmiller.io/"
languageCode = "en-us"
title = "jamesmiller.io"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-73168329-1"
# Define the number of posts per site
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "casper"
#theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    logo = "img/boatavatar.jpg"
    # Tell me who you are
    author = "James Miller"
    authorthumbnail = "img/boatavatar.jpg"
    bio = "Programmer - Father - Human"
    location = "Fruit Cove FL"
    #site_description = ""
    description = "Developer, Tinkerer, Gamer, Father."
    copyright  = ""
    avatar = "css/images/james.avatar.jpg"
    #cover = "https://dl.dropboxusercontent.com/u/149863/RoAbm5d.png"
    #cover = "https://dl.dropboxusercontent.com/u/149863/IMG_8447.JPG"
    #cover = "https://dl.dropboxusercontent.com/u/149863/IMG_0117_Cropped.JPG"
    cover = "img/px_by_Gre3g_@2X.png"
    # Format dates with Go's time formatting
    date_format = "2006-01-02"
    githubName = "jamesmillerio"
    twitterName = "jamesmillerio"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/jamesmillerio"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "jamesmillerio"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = "s13james"
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = "jamesmillerio"
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "jamesmillerio"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

[[menu.main]]
    name = "Home"
    pre = "<h3>Blog</h3>"
    weight = -120
    identifier = "blog"
    url = "/"

[[menu.main]]
    name = "Twitter"
    pre = "<h3>Contact</h3>"
    weight = -110
    identifier = "twitter"
    url = "http://twitter.com/jamesmillerio"

[[menu.main]]
    name = "Github"
    weight = -100
    identifier = "github"
    url = "http://github.com/jamesmillerio"

[[menu.main]]
    name = "Stack Overflow"
    weight = -100
    identifier = "so"
    url = "http://stackoverflow.com/users/3552/jamesmillerio?tab=profile"

[[menu.main]]
    name = "Resume"
    weight = -90
    identifier = "email"
    url = "http://stackoverflow.com/cv/jamesmillerio"

